FROM python:3.10-slim

WORKDIR /app

COPY ./script/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./script/app.py .

COPY /docker_entrypoint.sh /
RUN chmod +x /docker_entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["/docker_entrypoint.sh"]
