FROM python:3.10

WORKDIR /app

# Copy the contents of the local "script" directory into the container at /app
COPY ./script /app

# Copy the model file into the /data directory in the container
COPY data/model.h5 /data/model.h5

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
