version: '2.7'
services:
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_DB: milestone_3
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  init-script:
    build:
      context: .
      dockerfile: Dockerfile_init
    depends_on:
      - postgres
    volumes:
      - model_volume:/app/model


  
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "postgres:5432", "--", "bash", "-c", "python3 script/1_main.py"]
    depends_on:
      - postgres
    volumes:
      - model_volume:/app/model

 

volumes:
  postgres-data:
  model_volume:
