version: '3'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile_flask
    ports:
      - "80:5000"
    volumes:
      - ./data:/data
      - ./script/static:/app/static
    depends_on:
      - postgres
      
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: milestone_3
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tantsuraviktoria@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"

  test_client:
    build:
      context: .
      dockerfile: Dockerfile_test_client
    depends_on:
      - flask_app

volumes:
  postgres_data:

