# Use an official Python runtime as a base image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the necessary files into the container
COPY wait-for-it.sh /app/
COPY /script/init_db.py /app/
COPY /script/1_main.py /app/


# Install any dependencies required by your initialization script
# For example, if you are using psycopg2 for PostgreSQL connections:
RUN pip install psycopg2-binary

# Define the command to run your initialization script
CMD ["./wait-for-it.sh", "postgres:5432", "--", "bash", "-c", "python /script/init_db.py"]
